Feature: 회사 엔티티, 회사 계정 엔티티 구현
yh0921k/keytree-api pull request #11
Opened 2023-09-11 14:57 UTC by ujamdev

---
### PR Type ✔️

- [x] Feature - 기능 개발
- [ ] Fix - 버그 수정
- [ ] Code Style - 코드 스타일
- [ ] Refactoring - 리팩토링
- [ ] Document - 문서
- [ ] Others - 빌드, 배포 및 의존성 등 기타사항

---
### Summary(요약) ⭐
회사 엔티티, 회사 계정 엔티티 구현
---
### Describe your changes(상세) 🧾
- Company.java
     - 아이디, 이름, 연락처, 주소 필드로 구성했습니다.
     - 회사마다 아이디가 다수로 존재할 경우를 생각하여 계정 정보를 company 엔티티에 구성하지 않았습니다.
- CompanyAccount.java
     - 아이디, 이름, 로그인아이디, 로그인비밀번호, 권한 필드로 구성했습니다.
     - 회사마다 아이디가 다수로 생길 수 있어 정규화하여 엔티티 구현했습니다.
     - 현재 권한 enum type은 개발 초기 단계여서 ADMIN만 구성해놓은 상태입니다.
     - 추후에 SUPER_ADMIN 등 여러 권한이 추가된다면 따로 추가가 필요할 것 같습니다.

---
### Issue Number or Link 🔗

---
### Reference

---

[//]: # (PR 타이틀은 "Type: 타이틀" 형식으로 작성)
[//]: # (Summary의 경우 작업의 전반적인 내용을 함축 및 요약하여 작성)
[//]: # (Describe your changes의 경우 무슨 상황에서 왜 이러한 변경이 필요했고, 어떻게 작업햇는지 상세 기술)
[//]: # (Issue의 경우 추후 필요시 사용)
[//]: # (Reference의 경우 해당 변경점에서 중요하게 찾아본 자료가 있거나, 이해하는데 도움이 되는 내용을 포함)

2023-09-13 01:15 UTC, yh0921k requested changes

2023-09-13 01:15 UTC, yh0921k commented on src/main/java/io/devlabs/keytree/domains/company/domain/Company.java
'회사' 대신 '기업'이라는 이름으로 통일하면 좋을것 같습니다.

2023-09-13 01:15 UTC, yh0921k commented on src/main/java/io/devlabs/keytree/domains/company/domain/Authority.java
> +}
```suggestion
public enum UserRole {
    MASTER("MASTER");
    ADMIN("ROLE_ADMIN");
    USER("ROLE_USER"),

    private final String authority;

    UserRole(String authority) {
        this.authority = authority;
    }

    public String getAuthority() {
        return authority;
    }
}
```
- SUPER_ADMIN, MASTER, ROOT 중에 어떤걸로 선택할지 조금 고민해보면 좋을것 같아요.
- 자바에서 enum은 많이 사용되는 문법이니 기본적인 것들을 조금 공부하고 쓰시면 좋을것 같아요.

2023-09-13 01:15 UTC, yh0921k commented on src/main/java/io/devlabs/keytree/domains/company/domain/CompanyAccount.java
> +}
```suggestion
// 클래스명 -> Admin 또는 AdminUser
public class Admin extends BaseTimeEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Comment("관리자 아이디")
    private Long id;

    @Column
    @NotNull
    @Comment("관리자명)
    private String name;

    @Column
    @NotNull
    @Comment("이메일")
    private String email;

    @Column
    @NotNull
    @Comment("비밀번호")
    private String password;

    // 변경된 enum에 대한 로직 추가
}
```
- enum을 엔티티 필드에서 컬럼으로 매핑하는 방식을 찾아보고 적용해주세요.

2023-09-13 12:42 UTC, ujamdev commented on src/main/java/io/devlabs/keytree/domains/company/domain/Company.java
기업이라는 이름으로 통일했습니다.

2023-09-13 12:44 UTC, ujamdev commented on src/main/java/io/devlabs/keytree/domains/company/domain/Authority.java
> +}
MASTER, ADMIN, USER가 더욱 직관적일 것 같아서 제안 주신 코드로 적용했습니다.

2023-09-13 12:46 UTC, ujamdev commented on src/main/java/io/devlabs/keytree/domains/company/domain/CompanyAccount.java
> +}
엔티티에서 enum 매핑할 때 @Enumerated 어노테이션 적용하여 수정했습니다.

2023-09-16 12:42 UTC, yh0921k requested changes

2023-09-16 12:42 UTC, yh0921k commented on src/main/java/io/devlabs/keytree/domains/company/domain/CompanyAccount.java
> +    private UserRole authority;
변수명 데이터타입에 맞게 userRole로 변경해주세요.

2023-09-16 12:42 UTC, yh0921k commented on src/main/java/io/devlabs/keytree/domains/company/domain/UserRole.java
> +    ;
```suggestion
    MASTER("MASTER"),
    ADMIN("ADMIN"),
    USER("USER");
```
- 7번 라인 세미콜론 오탈자 정리 해주시고 ADMIN, USER로 가죠 MASTER는 Prefix 안붙으니까 이상한데

2023-09-16 12:42 UTC, yh0921k commented on src/main/java/io/devlabs/keytree/domains/company/domain/UserRole.java
> +}
```suggestion
    private final String name;

    UserRole(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
```
- Authority / Role이 추후 시큐리티 도입시 차이가 있습니다. 반영할때 편하게 미리 학습하시면 좋을듯 합니다.
- 해당 코드 부분에서는 authority를 그냥 name이라는 명명 쓰시면 될것 같아요.

2023-09-16 12:42 UTC, yh0921k commented on src/main/java/io/devlabs/keytree/domains/company/domain/Admin.java
> +}
```suggestion
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Comment("관리자 아이디")
    private Long id;

    @Column
    @NotNull
    @Comment("이름")
    private String name;

    @Column
    @NotNull
    @Comment("이메일")
    private String email;

    @Column
    @NotNull
    @Comment("비밀번호")
    private String password;

    @Column
    @NotNull
    @Enumerated(EnumType.STRING)
    @Comment("관리자 권한")
    private UserRole userRole;
}
```
- 아이디 정책이 현재 메일이라 email로 사용하는 편이 나을것 같습니다.
- 이외 코멘트 변경, 역할 관련 필드명 변경 있습니다.

2023-09-21 13:31 UTC, merged