feat: 퇴근 등록 API 구현
yh0921k/keytree-api pull request #6
Opened 2023-09-01 18:57 UTC by ujamdev

---
### PR Type ✔️

- [x] Feature - 기능 개발
- [ ] Fix - 버그 수정
- [ ] Code Style - 코드 스타일
- [ ] Refactoring - 리팩토링
- [ ] Document - 문서
- [ ] Others - 빌드, 배포 및 의존성 등 기타사항

---
### Summary(요약) ⭐
퇴근 등록 API 구현
---
### Describe your changes(상세) 🧾
**퇴근 생성 DTO**
 - 출근 생성 DTO는 초기 구현 단계여서 필수로 예상되는 필드로 구성했습니다.
 - 퇴근일시 필드 구성

**퇴근 생성 로직**
- 퇴근 시 출석고유아이디와 퇴근일시 값을가지고 고유아이디에 해당하는 attendance raw를 수정합니다.
- 출근과 퇴근을 raw로 관리를 할 수 있을 것 같아 해당 프로세스 로 구성했습니다.

**퇴근 생성 서비스 테스트 코드**
- 퇴근 로직 수행 후 attendanceId와 finishedAt 검증

**퇴근 생성 핸들러 테스트 코드**
- 출근 등록을 먼저 실시한 후 출근 등록한 곳에서 id값 추출하여 attendanceId에 할당합니다.
- 해당 attendanceId를 pathParam에 주입하여 테스트 코드를 구성했습니다.
---
### Issue Number or Link 🔗

---
### Reference

---

[//]: # (PR 타이틀은 "Type: 타이틀" 형식으로 작성)
[//]: # (Summary의 경우 작업의 전반적인 내용을 함축 및 요약하여 작성)
[//]: # (Describe your changes의 경우 무슨 상황에서 왜 이러한 변경이 필요했고, 어떻게 작업햇는지 상세 기술)
[//]: # (Issue의 경우 추후 필요시 사용)
[//]: # (Reference의 경우 해당 변경점에서 중요하게 찾아본 자료가 있거나, 이해하는데 도움이 되는 내용을 포함)

2023-09-02 10:09 UTC, yh0921k commented
- Attendance 도메인 application 레이어가 이상합니다. 다른 패키지 보고 변경해주세요.

2023-09-02 10:22 UTC, yh0921k requested changes

2023-09-02 10:22 UTC, yh0921k commented on src/main/java/io/devlabs/keytree/domains/attendance/application/dto/CreateFinishAttendanceResponse.java
> +    private Long userId;
- 퇴근 요청시 userId 반환하는 이유가 따로 있나요?

2023-09-02 10:22 UTC, yh0921k commented on src/main/java/io/devlabs/keytree/domains/attendance/domain/Attendance.java
> +    }
```java
public void finish(LocalDateTime finishedAt) {
        this.finishedAt = finishedAt;
}
```
- 변경 메서드의 경우 직관적으로 판단 가능할시 도메인 용어로 네이밍을 하는 것이 좋습니다.

---
```java
// Service Layer
attendance.finish( ... );
```
- 그럼 비즈니스 로직에서 직관적으로 코드가 읽힙니다.

2023-09-03 00:48 UTC, ujamdev commented on src/main/java/io/devlabs/keytree/domains/attendance/application/dto/CreateFinishAttendanceResponse.java
> +    private Long userId;
어떤 유저의 출퇴근 기록인지 알 필요가 있겠다라고 판단하여 userId를 반환하게끔 구성했어요

2023-09-03 00:54 UTC, ujamdev commented on src/main/java/io/devlabs/keytree/domains/attendance/domain/Attendance.java
> +    }
넵 직관적으로 판단 가능할 시 도메인 용어로 네이밍 구성할게요

2023-09-03 02:00 UTC, ujamdev commented
코멘트 주신 부분 반영 했습니다

2023-09-04 12:28 UTC, yh0921k commented
> * Attendance 도메인 application 레이어가 이상합니다. 다른 패키지 보고 변경해주세요.
> * 지금 코드 스타일이 전혀 적용된거 같지 않습니다.

- 위의 사항 다시 체크해주세요.

2023-09-04 12:50 UTC, ujamdev commented
attendance 도메인 application 다른 패키지와 상이한 부분 수정했습니다

2023-09-04 12:56 UTC, ujamX commented
> * Attendance 도메인 application 레이어가 이상합니다. 다른 패키지 보고 변경해주세요.
> * 지금 코드 스타일이 전혀 적용된거 같지 않습니다.
> * 위의 사항 다시 체크해주세요.

* attendance 도메인 application 구조 다른 패키지와 상이한 부분 수정했습니다

2023-09-04 13:24 UTC, yh0921k commented
[dc6876e](https://github.com/yh0921k/keytree-api/pull/6/commits/dc6876e41e8bfc85a4e0d3adb59167c73faefc20)
- 이 커밋은 무슨작업한거에요?

[385c32b](https://github.com/yh0921k/keytree-api/pull/6/commits/385c32bccbd36904eb3d2b2ecf7e720eead9bb9b)
- 이 커밋같은 경우는 타이틀 길이를 좀 줄이시면 좋을것 같아요
- ex) `올바르지 않은 패키지 구조 변경`
- 그리고 메시지에 왜 올바르지 않았고 어떻게 변경됏는지 적으시면 됩니다.

2023-09-04 13:34 UTC, ujamX commented
둘 다 패키지 구조 변경 건이어서 두개 묶어서 정리했습니다.

2023-09-04 13:45 UTC, yh0921k approved these changes

2023-09-04 13:45 UTC, merged